### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Frido-Cpp** [daredevilkinng/Telegram-Adder#1]
Hello bro, please do you have any Idea why telegram bans phone numbers some few minutes after login with telethon? I didn't use the phone numbers for any spamming activities., they just got banned few minutes after login
This just recently started, at first everything went good.
I am using real phone numbers not temp phone numbers.

**Comment by daredevilkinng** [comment]
Because you're using old scripts and those are based on single library named telethon. We have updated and made some new scripts for endless features check the channel

https://t.me/teleprotools

**Comment by Frido-Cpp** [comment]
how can I get the scripts?, I see only pictures in the channel

**Comment by daredevilkinng** [comment]
https://t.me/daredevilkinng

Ping me
